-- Assessment Questions (120 per role: FOH, BOH, Management)
-- START TRANSACTION;

DELETE FROM assessment_questions; -- Clear existing to avoid duplicates/confusion

-- Front of House (120 Questions) - Unchanged but included for completeness
INSERT INTO assessment_questions (role_type, category, question_text, is_validity) VALUES
-- Cooperativeness (20)
('foh', 'Cooperativeness', 'I often prioritize the team''s success over my personal recognition, even if it means staying late.', false),
('foh', 'Cooperativeness', 'I believe that following instructions is more important than taking initiative when the restaurant is busy.', false),
('foh', 'Cooperativeness', 'I would rather work with a difficult team that wins than a friendly team that loses.', false),
('foh', 'Cooperativeness', 'If a coworker is struggling, I will stop my own work to help them, even if it puts me behind.', false),
('foh', 'Cooperativeness', 'I find it easy to compromise when there is a disagreement about how to handle a table.', false),
('foh', 'Cooperativeness', 'I prefer a role where I implement others'' ideas rather than creating my own.', false),
('foh', 'Cooperativeness', 'I am comfortable taking direction from someone younger or less experienced than me.', false),
('foh', 'Cooperativeness', 'I believe that workplace harmony is essential for efficiency, even if it means suppressing some complaints.', false),
('foh', 'Cooperativeness', 'I willingly accept tasks that are not in my job description to help the restaurant run smoothly.', false),
('foh', 'Cooperativeness', 'I enjoy the feeling of being part of a large, synchronized machine.', false),
('foh', 'Cooperativeness', 'I rarely feel the need to challenge authority figures.', false),
('foh', 'Cooperativeness', 'I can work effectively with people I personally dislike.', false),
('foh', 'Cooperativeness', 'I believe that collective responsibility is better than individual accountability.', false),
('foh', 'Cooperativeness', 'I am always the first to volunteer for undesirable shifts to help the roster.', false),
('foh', 'Cooperativeness', 'I prefer group achievements to individual awards.', false),
('foh', 'Cooperativeness', 'I actively seek out opportunities to support colleagues who are overwhelmed.', false),
('foh', 'Cooperativeness', 'I engage in open communication even when the topic is uncomfortable.', false),
('foh', 'Cooperativeness', 'I value the opinions of my peers as much as my own.', false),
('foh', 'Cooperativeness', 'I believe that a good team player never gossips.', false),
('foh', 'Cooperativeness', 'I am willing to share my tips if it means the support staff are paid better.', false),
-- Personal Diplomacy (20)
('foh', 'Personal Diplomacy', 'I can maintain a friendly demeanor even when a customer is being unreasonable or insulting.', false),
('foh', 'Personal Diplomacy', 'I believe the customer is right, even when they are factually wrong.', false),
('foh', 'Personal Diplomacy', 'I find it easy to adjust my personality to match the energy of different guests.', false),
('foh', 'Personal Diplomacy', 'I can deliver bad news (like 86''d items) in a way that makes the guest thank me.', false),
('foh', 'Personal Diplomacy', 'I rarely take customer rudeness personally.', false),
('foh', 'Personal Diplomacy', 'I am comfortable engaging in small talk with strangers for extended periods.', false),
('foh', 'Personal Diplomacy', 'I can sense tension at a table before a complaint is even made.', false),
('foh', 'Personal Diplomacy', 'I know exactly when to step away from a table to give guests privacy.', false),
('foh', 'Personal Diplomacy', 'I can diffuse a heated situation without raising my voice.', false),
('foh', 'Personal Diplomacy', 'I enjoy the challenge of turning an unhappy guest into a loyal regular.', false),
('foh', 'Personal Diplomacy', 'I adapt my service style based on the age and mood of the guests.', false),
('foh', 'Personal Diplomacy', 'I am skilled at reading non-verbal cues.', false),
('foh', 'Personal Diplomacy', 'I believe that empathy is more important than efficiency in service.', false),
('foh', 'Personal Diplomacy', 'I can make a guest feel special in under 30 seconds.', false),
('foh', 'Personal Diplomacy', 'I handle VIP guests with same level of care as walk-ins.', false),
('foh', 'Personal Diplomacy', 'I avoid using negative language (like ''No'' or ''We can''t'') with guests.', false),
('foh', 'Personal Diplomacy', 'I am comfortable apologizing for mistakes I didn''t make.', false),
('foh', 'Personal Diplomacy', 'I can tactfully cut off a guest who has had too much to drink.', false),
('foh', 'Personal Diplomacy', 'I remember details about regular guests to build rapport.', false),
('foh', 'Personal Diplomacy', 'I treat delivery drivers and vendors with the same respect as paying customers.', false),
-- Patience (20)
('foh', 'Patience', 'I prefer a slow, steady pace over a chaotic rush.', false),
('foh', 'Patience', 'I can explain the menu to an indecisive table without checking my watch.', false),
('foh', 'Patience', 'I rarely get frustrated when I have to repeat myself.', false),
('foh', 'Patience', 'I stay calm when the kitchen crashes and food times exceed 45 minutes.', false),
('foh', 'Patience', 'I can handle a crying baby at a nearby table without losing focus.', false),
('foh', 'Patience', 'I believe that thoroughness is always better than speed.', false),
('foh', 'Patience', 'I don''t mind waiting for a table to turn if they are enjoying themselves.', false),
('foh', 'Patience', 'I can maintain a high level of service at the end of a double shift.', false),
('foh', 'Patience', 'I treat the 100th customer of the night with the same energy as the first.', false),
('foh', 'Patience', 'I handle tech issues (POS crashing) without vocal complaints.', false),
('foh', 'Patience', 'I am patient with trainees who make mistakes.', false),
('foh', 'Patience', 'I wait for guests to finish their sentences before responding.', false),
('foh', 'Patience', 'I remain composed when a guest changes their order multiple times.', false),
('foh', 'Patience', 'I understand that kitchen delays are rarely intentional.', false),
('foh', 'Patience', 'I take deep breaths instead of venting when stressed.', false),
('foh', 'Patience', 'I am willing to do repetitive side work (polishing) to perfection.', false),
('foh', 'Patience', 'I accept that some days will be harder than others.', false),
('foh', 'Patience', 'I don''t rush guests to pay the bill.', false),
('foh', 'Patience', 'I listen to manager feedback without interrupting.', false),
('foh', 'Patience', 'I can stand for 8 hours without showing physical fatigue to guests.', false),
-- Relaxed Attitude / Stress Tolerance (20)
('foh', 'Relaxed Attitude', 'I thrive in environments where everything seems to be going wrong.', false),
('foh', 'Relaxed Attitude', 'I rarely bring my personal problems to work.', false),
('foh', 'Relaxed Attitude', 'I can laugh off a mistake once it''s fixed.', false),
('foh', 'Relaxed Attitude', 'I sleep well even after a stressful shift.', false),
('foh', 'Relaxed Attitude', 'I view a full section as an opportunity, not a burden.', false),
('foh', 'Relaxed Attitude', 'I can multitask between 5 tables without writing everything down.', false),
('foh', 'Relaxed Attitude', 'Loud restaurant noise helps me focus rather than distracting me.', false),
('foh', 'Relaxed Attitude', 'I remain cheerful even when guests are visibly angry.', false),
('foh', 'Relaxed Attitude', 'I don''t get flustered when multiple tables sit at once.', false),
('foh', 'Relaxed Attitude', 'I can prioritize tasks instantly under pressure.', false),
('foh', 'Relaxed Attitude', 'I recover quickly from rejection.', false),
('foh', 'Relaxed Attitude', 'I enjoy the adrenaline of a Friday night dinner service.', false),
('foh', 'Relaxed Attitude', 'I can handle conflicting demands from management and guests.', false),
('foh', 'Relaxed Attitude', 'I don''t let one bad tip ruin my night.', false),
('foh', 'Relaxed Attitude', 'I am comfortable dealing with unexpected crises (power outage, spills).', false),
('foh', 'Relaxed Attitude', 'I maintain steady hands when carrying full trays.', false),
('foh', 'Relaxed Attitude', 'I speak slowly and clearly even when rushing.', false),
('foh', 'Relaxed Attitude', 'I help others relax when they are stressed.', false),
('foh', 'Relaxed Attitude', 'I find chaos somewhat organized.', false),
('foh', 'Relaxed Attitude', 'I am usually the calmest person in the room.', false),
-- Sales Aptitude (20)
('foh', 'Sales Aptitude', 'I believe that selling is serving.', false),
('foh', 'Sales Aptitude', 'I am comfortable recommending the most expensive wine if it pairs best.', false),
('foh', 'Sales Aptitude', 'I actively look for opportunities to increase the check average.', false),
('foh', 'Sales Aptitude', 'I can describe food in a way that makes people hungry.', false),
('foh', 'Sales Aptitude', 'I am not afraid of rejection when suggesting add-ons.', false),
('foh', 'Sales Aptitude', 'I view sales targets as a personal challenge to beat.', false),
('foh', 'Sales Aptitude', 'I research the menu to find selling points for every item.', false),
('foh', 'Sales Aptitude', 'I can read a table''s budget without asking.', false),
('foh', 'Sales Aptitude', 'I suggest bottled water over tap water by default.', false),
('foh', 'Sales Aptitude', 'I frame recommendations as ''favorites'' rather than ''upsells''.', false),
('foh', 'Sales Aptitude', 'I am persistent without being annoying.', false),
('foh', 'Sales Aptitude', 'I notice empty glasses immediately and offer another round.', false),
('foh', 'Sales Aptitude', 'I assume the guest wants dessert until they say no.', false),
('foh', 'Sales Aptitude', 'I start with premium options and work down.', false),
('foh', 'Sales Aptitude', 'I believe higher sales lead to better tips.', false),
('foh', 'Sales Aptitude', 'I can sell a dish I personally dislike.', false),
('foh', 'Sales Aptitude', 'I use positive reinforcement when guests order well.', false),
('foh', 'Sales Aptitude', 'I know the profit margins of items and push high-margin dishes.', false),
('foh', 'Sales Aptitude', 'I am competitive with other servers about sales numbers.', false),
('foh', 'Sales Aptitude', 'I believe every guest adds value to the business.', false),
-- Achievement / Validity (20)
('foh', 'Achievement', 'I am never satisfied with ''good enough''.', false),
('foh', 'Achievement', 'I constantly seek feedback to improve my skills.', false),
('foh', 'Achievement', 'I want to be a manager or owner one day.', false),
('foh', 'Achievement', 'I analyze my mistakes to ensure they don''t happen again.', false),
('foh', 'Achievement', 'I prepare for my shift as if it were an exam.', false),
('foh', 'Achievement', 'I take pride in the crispness of my uniform.', false),
('foh', 'Achievement', 'I view hospitality as a professional career.', false),
('foh', 'Achievement', 'I am willing to study menus on my own time.', false),
('foh', 'Achievement', 'I set daily goals for myself.', false),
('foh', 'Achievement', 'I enjoy being the best server on the floor.', false),
('foh', 'Validity', 'I have never been late to anything in my life.', true),
('foh', 'Validity', 'I like every single person I have ever met.', true),
('foh', 'Validity', 'I have never told a lie, even a white lie.', true),
('foh', 'Validity', 'I am always happy.', true),
('foh', 'Validity', 'I have never made a mistake at work.', true),
('foh', 'Validity', 'I check my phone zero times a day.', true),
('foh', 'Validity', 'I never get tired.', true),
('foh', 'Validity', 'I love all my bosses equally.', true),
('foh', 'Validity', 'I have never dropped a plate.', true),
('foh', 'Validity', 'I am perfect.', true);

-- Back of House (120 Questions) - REVISED (Removed Grunt Work/Potato Peeling)
INSERT INTO assessment_questions (role_type, category, question_text, is_validity) VALUES
-- Resilience & Stamina (20) - Renamed from Patience to be more professional
('boh', 'Resilience', 'I can maintain high energy levels throughout a long service.', false),
('boh', 'Resilience', 'I stay focused on quality even when performing repetitive tasks.', false),
('boh', 'Resilience', 'I value consistency over creativity in a high-volume kitchen.', false),
('boh', 'Resilience', 'I prefer to master one station before moving to another.', false),
('boh', 'Resilience', 'I find satisfaction in a perfectly organized prep list.', false),
('boh', 'Resilience', 'I strictly adhere to standard operating procedures.', false),
('boh', 'Resilience', 'I am meticulous about labelling and organization.', false),
('boh', 'Resilience', 'I can wait for a slow-braised dish without checking it unnecessary times.', false),
('boh', 'Resilience', 'I check the internal temperature of food multiple times to ensure safety.', false),
('boh', 'Resilience', 'I clean as I go, ensuring a spotless station at all times.', false),
('boh', 'Resilience', 'I prioritize precision in my knife work over speed when necessary.', false),
('boh', 'Resilience', 'I remain professional when servers ask clarifying questions.', false),
('boh', 'Resilience', 'I wait for equipment to reach optimal temperature before use.', false),
('boh', 'Resilience', 'I handle timing on the grill station with patience and accuracy.', false),
('boh', 'Resilience', 'I take pride in maintaining the cleanliness of deep-cleaning areas.', false),
('boh', 'Resilience', 'I respect the time and effort required to produce high-quality food.', false),
('boh', 'Resilience', 'I am willing to mentor junior staff on proper techniques.', false),
('boh', 'Resilience', 'I complete every task to 100% before starting the next.', false),
('boh', 'Resilience', 'I double-check my station setup before every service.', false),
('boh', 'Resilience', 'I maintain a calm and professional demeanor during busy periods.', false),
-- Stress Tolerance (20)
('boh', 'Stress Tolerance', 'I perform at my best when the kitchen is under pressure.', false),
('boh', 'Stress Tolerance', 'I find a busy service environment stimulating.', false),
('boh', 'Stress Tolerance', 'I can make decisive choices quickly during a rush.', false),
('boh', 'Stress Tolerance', 'I maintain focus in a loud and active environment.', false),
('boh', 'Stress Tolerance', 'I recover quickly and learn from mistakes made during service.', false),
('boh', 'Stress Tolerance', 'I prioritize accuracy over speed, even when tickets pile up.', false),
('boh', 'Stress Tolerance', 'I can effectively manage multiple orders simultaneously.', false),
('boh', 'Stress Tolerance', 'I handle feedback from the Head Chef constructively.', false),
('boh', 'Stress Tolerance', 'I stay focused when temperature conditions in the kitchen increase.', false),
('boh', 'Stress Tolerance', 'I coordinate seamlessly with other stations without needing visual cues.', false),
('boh', 'Stress Tolerance', 'I speak loudly and clearly to ensure communication during stress.', false),
('boh', 'Stress Tolerance', 'I focus on solutions rather than problems when errors occur.', false),
('boh', 'Stress Tolerance', 'I view a challenging service as an opportunity to demonstrate skill.', false),
('boh', 'Stress Tolerance', 'I accommodate special dietary requests without frustration.', false),
('boh', 'Stress Tolerance', 'I ensure my station remains sanitary even during peak hours.', false),
('boh', 'Stress Tolerance', 'I support the dishwashing team when they are under pressure.', false),
('boh', 'Stress Tolerance', 'I maintain high standards even after many consecutive workdays.', false),
('boh', 'Stress Tolerance', 'I compartmentalize personal issues to focus on my work.', false),
('boh', 'Stress Tolerance', 'I remain professional when front-of-house staff make errors.', false),
('boh', 'Stress Tolerance', 'I use breathing techniques to manage stress levels.', false),
-- Teamwork (20)
('boh', 'Teamwork', 'I respect the established kitchen hierarchy.', false),
('boh', 'Teamwork', 'I acknowledge and execute instructions immediately.', false),
('boh', 'Teamwork', 'I believe my station''s success contributes to the team''s success.', false),
('boh', 'Teamwork', 'I constantly communicate my position to ensure safety (e.g., ''Behind'', ''Hot'').', false),
('boh', 'Teamwork', 'I proactively ask for assistance before falling behind.', false),
('boh', 'Teamwork', 'I assist colleagues with their station breakdown after finishing mine.', false),
('boh', 'Teamwork', 'I share my culinary knowledge with anyone who asks.', false),
('boh', 'Teamwork', 'I ensure equipment and ingredients are accessible to everyone.', false),
('boh', 'Teamwork', 'I trust my colleagues to execute their roles effectively.', false),
('boh', 'Teamwork', 'I cover shifts for colleagues who are unwell without resentment.', false),
('boh', 'Teamwork', 'I treat all staff members, including stewards, with respect.', false),
('boh', 'Teamwork', 'I avoid engaging in non-constructive workplace discussions.', false),
('boh', 'Teamwork', 'I own up to my errors immediately to the team.', false),
('boh', 'Teamwork', 'I synchronize my plating times with the expo/pass.', false),
('boh', 'Teamwork', 'I ask permission before borrowing tools from others.', false),
('boh', 'Teamwork', 'I ensure the line stays hydrated during service.', false),
('boh', 'Teamwork', 'I respect shared storage spaces like the walk-in cooler.', false),
('boh', 'Teamwork', 'I prioritize the quality of the dish over my ego.', false),
('boh', 'Teamwork', 'I actively listen when others are speaking.', false),
('boh', 'Teamwork', 'I value feedback from FOH staff regarding dish quality.', false),
-- Attention to Detail (20)
('boh', 'Attention to Detail', 'I follow recipes with precision, measuring to the gram.', false),
('boh', 'Attention to Detail', 'I can identify when a sauce needs minor adjustments.', false),
('boh', 'Attention to Detail', 'I believe plating aesthetics are as critical as flavor.', false),
('boh', 'Attention to Detail', 'I sharpen my knives before every shift to ensure precision.', false),
('boh', 'Attention to Detail', 'I adhere strictly to FIFO (First In, First Out) principles.', false),
('boh', 'Attention to Detail', 'I identify and mitigate cross-contamination risks immediately.', false),
('boh', 'Attention to Detail', 'I taste every component I prepare.', false),
('boh', 'Attention to Detail', 'I label all prepped items with clear dates and descriptions.', false),
('boh', 'Attention to Detail', 'I ensure plate rims are spotless before service.', false),
('boh', 'Attention to Detail', 'I check the quality of fresh produce upon delivery.', false),
('boh', 'Attention to Detail', 'I notice immediately if equipment is malfunctioning.', false),
('boh', 'Attention to Detail', 'I rely on measurements rather than estimation for seasoning.', false),
('boh', 'Attention to Detail', 'I clean areas of my station that are not immediately visible.', false),
('boh', 'Attention to Detail', 'I double-check tickets with allergy alerts.', false),
('boh', 'Attention to Detail', 'I believe consistency is the hallmark of a professional chef.', false),
('boh', 'Attention to Detail', 'I promote hand-washing hygiene among peers.', false),
('boh', 'Attention to Detail', 'I ensure my uniform is clean and pressed.', false),
('boh', 'Attention to Detail', 'I meticulously track food waste.', false),
('boh', 'Attention to Detail', 'I am attentive to the temperature of the plates used for service.', false),
('boh', 'Attention to Detail', 'I organize linens and towels neatly.', false),
-- Professionalism (20)
('boh', 'Reliability', 'I adhere to my scheduled start times strictly.', false),
('boh', 'Reliability', 'I maintain attendance even during minor personal inconveniences.', false),
('boh', 'Reliability', 'I ensure my station is fully stocked for the next shift.', false),
('boh', 'Reliability', 'I stay until all closing duties are completed to standard.', false),
('boh', 'Reliability', 'I respect the inventory and do not consume product without authorization.', false),
('boh', 'Reliability', 'I am mindful of food cost and waste management.', false),
('boh', 'Reliability', 'I report any breakage or damage immediately.', false),
('boh', 'Reliability', 'I follow safety protocols even when unsupervised.', false),
('boh', 'Reliability', 'I maintain strict personal hygiene standards.', false),
('boh', 'Reliability', 'I refrain from using personal devices in the kitchen.', false),
('boh', 'Reliability', 'I proactively seek additional tasks during downtime.', false),
('boh', 'Reliability', 'I perform inventory counts with high accuracy.', false),
('boh', 'Reliability', 'I treat kitchen equipment with care and respect.', false),
('boh', 'Reliability', 'I view culinary arts as my long-term career.', false),
('boh', 'Reliability', 'I honor my commitments to the team.', false),
('boh', 'Reliability', 'I take closing checklists seriously and verify them.', false),
('boh', 'Reliability', 'I communicate my schedule availability clearly and in advance.', false),
('boh', 'Reliability', 'I arrive at work sober and ready to focus.', false),
('boh', 'Reliability', 'I handle cleaning chemicals according to safety data sheets.', false),
('boh', 'Reliability', 'I lead by example in work ethic and attitude.', false),
-- Validity (20)
('boh', 'Validity', 'I have never made a mistake in the kitchen.', true),
('boh', 'Validity', 'I never feel physical pain.', true),
('boh', 'Validity', 'I have never disagreed with a Chef in my head.', true),
('boh', 'Validity', 'I am always 100% focused every second of the day.', true),
('boh', 'Validity', 'I enjoy cleaning grease traps more than cooking.', true),
('boh', 'Validity', 'I never experience fatigue after a double shift.', true),
('boh', 'Validity', 'I know everything there is to know about cooking.', true),
('boh', 'Validity', 'I have never burned a piece of toast.', true),
('boh', 'Validity', 'I am faster than a robotic arm.', true),
('boh', 'Validity', 'I never feel the need to hydrate.', true),
('boh', 'Validity', 'I have never been annoyed by a difficult ticket.', true),
('boh', 'Validity', 'I like every single food ingredient in existence.', true),
('boh', 'Validity', 'I never use the restroom during work hours.', true),
('boh', 'Validity', 'I function like a machine, not a human.', true),
('boh', 'Validity', 'I have never been late to any event in my life.', true),
('boh', 'Validity', 'I remember every order I have ever cooked.', true),
('boh', 'Validity', 'I smile continuously for 12 hours straight.', true),
('boh', 'Validity', 'I have never had a minor kitchen injury.', true),
('boh', 'Validity', 'I can recite every recipe in the world by heart.', true),
('boh', 'Validity', 'I am flawless.', true);

-- Management (120 Questions) - NEW
INSERT INTO assessment_questions (role_type, category, question_text, is_validity) VALUES
-- Leadership & Culture (20)
('top_roles', 'Leadership', 'I believe culture eats strategy for breakfast.', false),
('top_roles', 'Leadership', 'I prefer to lead by example rather than just giving orders.', false),
('top_roles', 'Leadership', 'I am comfortable having difficult conversations with underperforming staff.', false),
('top_roles', 'Leadership', 'I prioritize my team''s development over my own convenience.', false),
('top_roles', 'Leadership', 'I believe in praising in public and correcting in private.', false),
('top_roles', 'Leadership', 'I can rally the team during a disastrous shift without losing my cool.', false),
('top_roles', 'Leadership', 'I actively listen to staff concerns even if I cannot solve them immediately.', false),
('top_roles', 'Leadership', 'I believe a manager works for their staff, not the other way around.', false),
('top_roles', 'Leadership', 'I am willing to wash dishes or bus tables if the team needs help.', false),
('top_roles', 'Leadership', 'I take full responsibility for my team''s failures.', false),
('top_roles', 'Leadership', 'I give full credit to my team for our successes.', false),
('top_roles', 'Leadership', 'I focus on solutions rather than blaming individuals.', false),
('top_roles', 'Leadership', 'I am transparent with my team about business challenges.', false),
('top_roles', 'Leadership', 'I consistently enforce standards, even when it is unpopular.', false),
('top_roles', 'Leadership', 'I invest time in training rather than complaining about lack of skills.', false),
('top_roles', 'Leadership', 'I respect boundaries between professional and personal relationships.', false),
('top_roles', 'Leadership', 'I can motivate diverse personalities towards a common goal.', false),
('top_roles', 'Leadership', 'I handle conflict between staff members impartially.', false),
('top_roles', 'Leadership', 'I create an environment where staff feel safe to admit mistakes.', false),
('top_roles', 'Leadership', 'I measure my success by how many leaders I create.', false),
-- Operations & Efficiency (20)
('top_roles', 'Operations', 'I notice when labor costs are running high mid-shift.', false),
('top_roles', 'Operations', 'I constantly look for ways to optimize workflow.', false),
('top_roles', 'Operations', 'I believe accurate inventory is the backbone of profitability.', false),
('top_roles', 'Operations', 'I can troubleshoot POS or equipment issues quickly.', false),
('top_roles', 'Operations', 'I ensure health and safety compliance is never compromised.', false),
('top_roles', 'Operations', 'I structure schedules to balance budget and service needs.', false),
('top_roles', 'Operations', 'I am proactive about maintenance before equipment breaks down.', false),
('top_roles', 'Operations', 'I analyze product mix reports to adjust menu strategy.', false),
('top_roles', 'Operations', 'I ensure shift handovers are detailed and effective.', false),
('top_roles', 'Operations', 'I can run the pass/expo effectively during peak service.', false),
('top_roles', 'Operations', 'I notice small details like lighting and music volume immediately.', false),
('top_roles', 'Operations', 'I have a system for tracking and reducing waste.', false),
('top_roles', 'Operations', 'I prioritize guest flow management to maximize table turns.', false),
('top_roles', 'Operations', 'I ensure opening and closing checklists are actually completed.', false),
('top_roles', 'Operations', 'I can adapt the floor plan instantly for unexpected large groups.', false),
('top_roles', 'Operations', 'I manage vendor relationships to ensure quality and timeliness.', false),
('top_roles', 'Operations', 'I enforce standard recipe adherence to control food cost.', false),
('top_roles', 'Operations', 'I have a plan for every likely emergency scenario.', false),
('top_roles', 'Operations', 'I audit cash handling procedures regularly.', false),
('top_roles', 'Operations', 'I believe operations should run smoothly even when I am not there.', false),
-- Financial Acumen (20)
('top_roles', 'Financials', 'I understand the difference between COGS and Prime Cost.', false),
('top_roles', 'Financials', 'I review the P&L statement to identify areas for improvement.', false),
('top_roles', 'Financials', 'I understand how small variances in portioning affect the bottom line.', false),
('top_roles', 'Financials', 'I treat the business''s money as if it were my own.', false),
('top_roles', 'Financials', 'I can calculate food cost percentage manually if needed.', false),
('top_roles', 'Financials', 'I understand the impact of overtime on labor targets.', false),
('top_roles', 'Financials', 'I negotiate with suppliers for better pricing or terms.', false),
('top_roles', 'Financials', 'I forecast sales accurately to plan purchasing.', false),
('top_roles', 'Financials', 'I educate staff on how their actions impact profitability.', false),
('top_roles', 'Financials', 'I monitor voids and comps for suspicious patterns.', false),
('top_roles', 'Financials', 'I understand the concept of menu engineering.', false),
('top_roles', 'Financials', 'I focus on driving top-line sales, not just cutting costs.', false),
('top_roles', 'Financials', 'I understand return on investment (ROI) for marketing initiatives.', false),
('top_roles', 'Financials', 'I manage par levels effectively to prevent overstocking.', false),
('top_roles', 'Financials', 'I track average spend per head (check average) daily.', false),
('top_roles', 'Financials', 'I understand the fixed vs variable costs of the restaurant.', false),
('top_roles', 'Financials', 'I set clear financial targets for the team.', false),
('top_roles', 'Financials', 'I review daily sales reports before leaving.', false),
('top_roles', 'Financials', 'I understand the cost of employee turnover.', false),
('top_roles', 'Financials', 'I make data-driven decisions.', false),
-- Customer Experience (20)
('top_roles', 'CX', 'I believe the guest experience starts before they walk in the door.', false),
('top_roles', 'CX', 'I empower staff to resolve guest complaints immediately.', false),
('top_roles', 'CX', 'I touch every table during service.', false),
('top_roles', 'CX', 'I read and respond to online reviews constructively.', false),
('top_roles', 'CX', 'I view a complaint as a gift and an opportunity to improve.', false),
('top_roles', 'CX', 'I ensure the ambiance aligns with the brand concept.', false),
('top_roles', 'CX', 'I protect guests from internal kitchen or staff chaos.', false),
('top_roles', 'CX', 'I train the team on the art of anticipation.', false),
('top_roles', 'CX', 'I believe in the power of "Yes".', false),
('top_roles', 'CX', 'I handle intoxicated guests with firm care.', false),
('top_roles', 'CX', 'I remember the names and preferences of regular guests.', false),
('top_roles', 'CX', 'I ensure the bathrooms are checked every 30 minutes.', false),
('top_roles', 'CX', 'I model superior hospitality in every interaction.', false),
('top_roles', 'CX', 'I ensure wait times are quoted accurately.', false),
('top_roles', 'CX', 'I follow up on recovered guests to ensure satisfaction.', false),
('top_roles', 'CX', 'I believe consistency is the key to guest loyalty.', false),
('top_roles', 'CX', 'I notice when a guest is left unattended for too long.', false),
('top_roles', 'CX', 'I create "wow" moments for special occasions.', false),
('top_roles', 'CX', 'I solicit honest feedback from guests table-side.', false),
('top_roles', 'CX', 'I ensure the food looks as good as it tastes.', false),
-- Emotional Intelligence (20)
('top_roles', 'EQ', 'I remain calm when everyone else is panicking.', false),
('top_roles', 'EQ', 'I can separate my personal feelings from professional decisions.', false),
('top_roles', 'EQ', 'I sense the "mood in the room" immediately.', false),
('top_roles', 'EQ', 'I adapt my communication style to different employees.', false),
('top_roles', 'EQ', 'I handle rejection or bad news with resilience.', false),
('top_roles', 'EQ', 'I am self-aware of my own stress triggers.', false),
('top_roles', 'EQ', 'I can empathize with an angry guest without taking abuse.', false),
('top_roles', 'EQ', 'I know when to push the team and when to back off.', false),
('top_roles', 'EQ', 'I do not hold grudges.', false),
('top_roles', 'EQ', 'I reflect on my interactions to improve next time.', false),
('top_roles', 'EQ', 'I celebrate small wins to keep morale high.', false),
('top_roles', 'EQ', 'I am approachable but respected.', false),
('top_roles', 'EQ', 'I can de-escalate conflicts between BOH and FOH.', false),
('top_roles', 'EQ', 'I listen more than I speak.', false),
('top_roles', 'EQ', 'I trust my intuition but verify with facts.', false),
('top_roles', 'EQ', 'I am comfortable with ambiguity.', false),
('top_roles', 'EQ', 'I manage my energy levels to last the whole shift.', false),
('top_roles', 'EQ', 'I am patient with the learning process of others.', false),
('top_roles', 'EQ', 'I express gratitude sincerely.', false),
('top_roles', 'EQ', 'I maintain professional boundaries.', false),
-- Validity (20)
('top_roles', 'Validity', 'I have never made a bad decision.', true),
('top_roles', 'Validity', 'I know absolutely everything about running a restaurant.', true),
('top_roles', 'Validity', 'I never get stressed.', true),
('top_roles', 'Validity', 'I am loved by every single person I have ever met.', true),
('top_roles', 'Validity', 'I have never been late in my entire career.', true),
('top_roles', 'Validity', 'I never need to ask for help.', true),
('top_roles', 'Validity', 'I have zero weaknesses.', true),
('top_roles', 'Validity', 'I work 24 hours a day without sleep.', true),
('top_roles', 'Validity', 'I have never forgotten a task.', true),
('top_roles', 'Validity', 'I assume every employee is perfect.', true),
('top_roles', 'Validity', 'I never check my phone.', true),
('top_roles', 'Validity', 'I have never felt angry at work.', true),
('top_roles', 'Validity', 'I am a machine.', true),
('top_roles', 'Validity', 'I have never had a conflict with anyone.', true),
('top_roles', 'Validity', 'I always know exactly what to say.', true),
('top_roles', 'Validity', 'I never make typos.', true),
('top_roles', 'Validity', 'I have never lost a receipt.', true),
('top_roles', 'Validity', 'I am always right.', true),
('top_roles', 'Validity', 'I have never felt tired.', true),
('top_roles', 'Validity', 'I am perfect.', true);

-- END TRANSACTION;
