-- Assessment Questions (120 per role)

-- Front of House (120 Questions)
INSERT INTO assessment_questions (role_type, category, question_text, is_validity) VALUES
-- Cooperativeness (20)
('foh', 'Cooperativeness', 'I enjoy working closely with others to get the job done.', false),
('foh', 'Cooperativeness', 'I am always willing to help a coworker, even if I am busy.', false),
('foh', 'Cooperativeness', 'I prefer working in a team rather than alone.', false),
('foh', 'Cooperativeness', 'It is important to me that everyone on the team gets along.', false),
('foh', 'Cooperativeness', 'I often put the team needs above my own.', false),
('foh', 'Cooperativeness', 'I don''t mind taking instructions from others.', false),
('foh', 'Cooperativeness', 'I believe group success is more important than individual credit.', false),
('foh', 'Cooperativeness', 'I am quick to resolve conflicts with colleagues.', false),
('foh', 'Cooperativeness', 'I adapt easily to different working styles.', false),
('foh', 'Cooperativeness', 'I support team decisions even if I disagree initially.', false),
('foh', 'Cooperativeness', 'I actively look for ways to make my coworkers'' jobs easier.', false),
('foh', 'Cooperativeness', 'I share information openely with my team.', false),
('foh', 'Cooperativeness', 'I am comfortable with shared responsibility.', false),
('foh', 'Cooperativeness', 'I prioritize team harmony.', false),
('foh', 'Cooperativeness', 'I am willing to cover shifts for others.', false),
('foh', 'Cooperativeness', 'I listen to others'' ideas before speaking.', false),
('foh', 'Cooperativeness', 'I check in with colleagues to see if they need help.', false),
('foh', 'Cooperativeness', 'I avoid gossiping about coworkers.', false),
('foh', 'Cooperativeness', 'I treat all team members with respect.', false),
('foh', 'Cooperativeness', 'I believe a happy team leads to happy customers.', false),

-- Personal Diplomacy / Communication (20)
('foh', 'Personal Diplomacy', 'I can easily talk to people I have just met.', false),
('foh', 'Personal Diplomacy', 'I am good at sensing how others are feeling.', false),
('foh', 'Personal Diplomacy', 'I know how to deliver bad news without making people angry.', false),
('foh', 'Personal Diplomacy', 'I am polite even when people are rude to me.', false),
('foh', 'Personal Diplomacy', 'I enjoy meeting new people every day.', false),
('foh', 'Personal Diplomacy', 'I can easily find common ground with anyone.', false),
('foh', 'Personal Diplomacy', 'I make eye contact when speaking to guests.', false),
('foh', 'Personal Diplomacy', 'I remember regular customers'' names and preferences.', false),
('foh', 'Personal Diplomacy', 'I can explain complex menu items simply.', false),
('foh', 'Personal Diplomacy', 'I know when to chat and when to leave a guest alone.', false),
('foh', 'Personal Diplomacy', 'I am comfortable engaging with diverse groups of people.', false),
('foh', 'Personal Diplomacy', 'I smile even when I don''t feel like it.', false),
('foh', 'Personal Diplomacy', 'I never interrupt a customer while they are speaking.', false),
('foh', 'Personal Diplomacy', 'I can handle difficult questions with grace.', false),
('foh', 'Personal Diplomacy', 'I apologize sincerely when things go wrong.', false),
('foh', 'Personal Diplomacy', 'I am conscious of my body language.', false),
('foh', 'Personal Diplomacy', 'I speak clearly and confidently.', false),
('foh', 'Personal Diplomacy', 'I avoid using slang with guests.', false),
('foh', 'Personal Diplomacy', 'I can read the mood of a table instantly.', false),
('foh', 'Personal Diplomacy', 'I make every guest feel like a VIP.', false),

-- Patience (20)
('foh', 'Patience', 'I rarely get annoyed by slow customers.', false),
('foh', 'Patience', 'I can wait for long periods without getting frustrated.', false),
('foh', 'Patience', 'I stay calm when things don''t go as planned.', false),
('foh', 'Patience', 'I don''t mind explaining things multiple times to guests.', false),
('foh', 'Patience', 'I take my time to listen to customer complaints fully.', false),
('foh', 'Patience', 'Rushing through tasks makes me uncomfortable; I prefer a steady pace.', false),
('foh', 'Patience', 'I handle indecisive customers with a smile.', false),
('foh', 'Patience', 'I do not show frustration when the kitchen is slow.', false),
('foh', 'Patience', 'I stay positive during long, slow shifts.', false),
('foh', 'Patience', 'I am patient with children in the restaurant.', false),
('foh', 'Patience', 'I repeat orders back to customers without annoyance.', false),
('foh', 'Patience', 'I deal with demanding guests without losing my cool.', false),
('foh', 'Patience', 'I accept that mistakes happen and fix them calmly.', false),
('foh', 'Patience', 'I don''t snap at colleagues when I am stressed.', false),
('foh', 'Patience', 'I wait for the right moment to interrupt a conversation.', false),
('foh', 'Patience', 'I take a deep breath before reacting to rudeness.', false),
('foh', 'Patience', 'I am willing to do tedious side work.', false),
('foh', 'Patience', 'I understand that quality takes time.', false),
('foh', 'Patience', 'I let customers take their time reading the menu.', false),
('foh', 'Patience', 'I remain courteous even at the end of a long shift.', false),

-- Stress Tolerance / Resilience (20)
('foh', 'Relaxed Attitude', 'I stay calm even when the restaurant is extremely busy.', false),
('foh', 'Relaxed Attitude', 'Loud noises and crowds do not bother me.', false),
('foh', 'Relaxed Attitude', 'I can handle multiple tables at once without panicking.', false),
('foh', 'Relaxed Attitude', 'I rarely feel overwhelmed by pressure.', false),
('foh', 'Relaxed Attitude', 'I find it easy to relax after a hard day''s work.', false),
('foh', 'Relaxed Attitude', 'Unexpected problems are just challenges to solve.', false),
('foh', 'Relaxed Attitude', 'I thrive in a high-energy environment.', false),
('foh', 'Relaxed Attitude', 'I can switch focus quickly between tasks.', false),
('foh', 'Relaxed Attitude', 'I don''t take customer complaints personally.', false),
('foh', 'Relaxed Attitude', 'I can function effectively with little sleep.', false),
('foh', 'Relaxed Attitude', 'I maintain my standard of service even during a rush.', false),
('foh', 'Relaxed Attitude', 'I am energized by a full house.', false),
('foh', 'Relaxed Attitude', 'I can handle conflicting demands from different tables.', false),
('foh', 'Relaxed Attitude', 'I recover quickly from a bad interaction.', false),
('foh', 'Relaxed Attitude', 'I keep a tidy section even when busy.', false),
('foh', 'Relaxed Attitude', 'I ask for help when I am in the weeds.', false),
('foh', 'Relaxed Attitude', 'I prioritize tasks effectively under pressure.', false),
('foh', 'Relaxed Attitude', 'I am resilient in the face of failure.', false),
('foh', 'Relaxed Attitude', 'I enjoy the physical demands of the job.', false),
('foh', 'Relaxed Attitude', 'I leave work stress at work.', false),

-- Sales Aptitude (20)
('foh', 'Sales Aptitude', 'I enjoy persuading people to try new things.', false),
('foh', 'Sales Aptitude', 'I feel comfortable suggesting expensive items to customers.', false),
('foh', 'Sales Aptitude', 'I see sales as helping the customer have a better experience.', false),
('foh', 'Sales Aptitude', 'I am confident in my ability to sell.', false),
('foh', 'Sales Aptitude', 'I like the challenge of increasing the bill size.', false),
('foh', 'Sales Aptitude', 'I can enthusiastically describe menu items.', false),
('foh', 'Sales Aptitude', 'I always recommend a starter or dessert.', false),
('foh', 'Sales Aptitude', 'I notice when glasses are empty and offer refills.', false),
('foh', 'Sales Aptitude', 'I highlight the specials to every table.', false),
('foh', 'Sales Aptitude', 'I believe in the quality of the food I serve.', false),
('foh', 'Sales Aptitude', 'I can upsell without being pushy.', false),
('foh', 'Sales Aptitude', 'I enjoy learning about wine and beverage pairings.', false),
('foh', 'Sales Aptitude', 'I create a desire for food through description.', false),
('foh', 'Sales Aptitude', 'I view every customer interaction as a sales opportunity.', false),
('foh', 'Sales Aptitude', 'I am motivated by sales targets.', false),
('foh', 'Sales Aptitude', 'I know the menu inside and out.', false),
('foh', 'Sales Aptitude', 'I can guide a guest to a decision quickly.', false),
('foh', 'Sales Aptitude', 'I suggest premium spirits over house pours.', false),
('foh', 'Sales Aptitude', 'I ask open-ended questions to gauge preferences.', false),
('foh', 'Sales Aptitude', 'I take pride in generating revenue for the restaurant.', false),

-- Achievement / Reliability (15)
('foh', 'Achievement', 'I always try to be the best at what I do.', false),
('foh', 'Achievement', 'I set high standards for myself.', false),
('foh', 'Achievement', 'I am constantly looking for ways to improve my performance.', false),
('foh', 'Achievement', 'Getting recognized for good work is important to me.', false),
('foh', 'Achievement', 'I enjoy competition and winning.', false),
('foh', 'Achievement', 'I am willing to work hard to get a promotion.', false),
('foh', 'Achievement', 'I am punctual and reliable.', false),
('foh', 'Achievement', 'I dress impeccably for work.', false),
('foh', 'Achievement', 'I follow all company policies strictly.', false),
('foh', 'Achievement', 'I double-check checks for accuracy.', false),
('foh', 'Achievement', 'I take ownership of my mistakes.', false),
('foh', 'Achievement', 'I go above and beyond for guests.', false),
('foh', 'Achievement', 'I seek feedback to grow professionally.', false),
('foh', 'Achievement', 'I help train new staff members.', false),
('foh', 'Achievement', 'I maintain a positive attitude at all times.', false),

-- Validity (5)
('foh', 'Validity', 'I have never once been annoyed by a customer.', true),
('foh', 'Validity', 'I have never made a mistake at work.', true),
('foh', 'Validity', 'I like every single person I have ever met.', true),
('foh', 'Validity', 'I am always happy, regardless of the situation.', true),
('foh', 'Validity', 'I have never told a small lie.', true);

-- Back of House (120 Questions)
INSERT INTO assessment_questions (role_type, category, question_text, is_validity) VALUES
-- Patience / Routine (20)
('boh', 'Patience', 'I can perform repetitive tasks without getting bored.', false),
('boh', 'Patience', 'I don''t mind waiting for others to finish their part of the job.', false),
('boh', 'Patience', 'I stay calm when orders pile up.', false),
('boh', 'Patience', 'I take the time to do things right, even when busy.', false),
('boh', 'Patience', 'I rarely lose my temper in the kitchen.', false),
('boh', 'Patience', 'I can handle long shifts without complaining.', false),
('boh', 'Patience', 'I enjoy chopping vegetables for hours.', false),
('boh', 'Patience', 'I finish cleaning duties thoroughly every night.', false),
('boh', 'Patience', 'I do not rush deep cleaning tasks.', false),
('boh', 'Patience', 'I wait for equipment to heat up properly.', false),
('boh', 'Patience', 'I am patient with new kitchen staff.', false),
('boh', 'Patience', 'I don''t mind doing the dishes if needed.', false),
('boh', 'Patience', 'I restock my station perfectly every time.', false),
('boh', 'Patience', 'I maintain focus during slow periods.', false),
('boh', 'Patience', 'I double-check prep lists without annoyance.', false),
('boh', 'Patience', 'I follow slow-cooking recipes precisely.', false),
('boh', 'Patience', 'I handle food returns without anger.', false),
('boh', 'Patience', 'I communicate delays calmly to the pass.', false),
('boh', 'Patience', 'I ensure proper rotation of stock (FIFO).', false),
('boh', 'Patience', 'I take time to label everything correctly.', false),

-- Stress Tolerance (20)
('boh', 'Stress Tolerance', 'I work best when under pressure.', false),
('boh', 'Stress Tolerance', 'A busy kitchen environment excites me.', false),
('boh', 'Stress Tolerance', 'I can make quick decisions during a rush.', false),
('boh', 'Stress Tolerance', 'Loud and chaotic environments do not distract me.', false),
('boh', 'Stress Tolerance', 'I recover quickly after a stressful service.', false),
('boh', 'Stress Tolerance', 'I can multitask effectively without dropping the ball.', false),
('boh', 'Stress Tolerance', 'I keep my station clean even during a rush.', false),
('boh', 'Stress Tolerance', 'Duplicate tickets do not flush me.', false),
('boh', 'Stress Tolerance', 'I can handle heat and physical discomfort.', false),
('boh', 'Stress Tolerance', 'I prioritize orders instantly in my head.', false),
('boh', 'Stress Tolerance', 'I support others when I am slammed.', false),
('boh', 'Stress Tolerance', 'I respond well to direct, loud commands.', false),
('boh', 'Stress Tolerance', 'I don''t freeze when mistakes happen.', false),
('boh', 'Stress Tolerance', 'I maintain plating standards when busy.', false),
('boh', 'Stress Tolerance', 'I can handle last-minute menu changes.', false),
('boh', 'Stress Tolerance', 'I keep a clear head during equipment failure.', false),
('boh', 'Stress Tolerance', 'I handle constructive criticism during service.', false),
('boh', 'Stress Tolerance', 'I pace myself for a 12-hour shift.', false),
('boh', 'Stress Tolerance', 'I resolve ticket confusion quickly.', false),
('boh', 'Stress Tolerance', 'I leave personal issues at the door.', false),

-- Teamwork (20)
('boh', 'Teamwork', 'I communicate clearly with my station partners.', false),
('boh', 'Teamwork', 'I am willing to cover for a coworker if they are behind.', false),
('boh', 'Teamwork', 'I respect the hierarchy in the kitchen.', false),
('boh', 'Teamwork', 'I believe the team''s success is more important than my own credit.', false),
('boh', 'Teamwork', 'I listen carefully to the Chef''s instructions.', false),
('boh', 'Teamwork', 'I avoid workplace gossip or conflict.', false),
('boh', 'Teamwork', 'I say "Yes, Chef" and execute.', false),
('boh', 'Teamwork', 'I help the dishwasher when I have downtime.', false),
('boh', 'Teamwork', 'I call back orders loud and clear.', false),
('boh', 'Teamwork', 'I clean up spills immediately for safety.', false),
('boh', 'Teamwork', 'I ask before borrowing someone''s knife.', false),
('boh', 'Teamwork', 'I respect shared spaces (walk-in, dry store).', false),
('boh', 'Teamwork', 'I coordinate timing with other stations.', false),
('boh', 'Teamwork', 'I offer water to the line during service.', false),
('boh', 'Teamwork', 'I teach others what I know.', false),
('boh', 'Teamwork', 'I admit when I don''t know how to do something.', false),
('boh', 'Teamwork', 'I treat FOH staff with respect.', false),
('boh', 'Teamwork', 'I ensure the next shift is set up for success.', false),
('boh', 'Teamwork', 'I participate in deep cleaning days.', false),
('boh', 'Teamwork', 'I celebrate the team''s good service.', false),

-- Attention to Detail (20)
('boh', 'Attention to Detail', 'I always follow recipes exactly as written.', false),
('boh', 'Attention to Detail', 'I notice small details that others might miss.', false),
('boh', 'Attention to Detail', 'Presentation is just as important as taste to me.', false),
('boh', 'Attention to Detail', 'I keep my workspace perfectly organized.', false),
('boh', 'Attention to Detail', 'I double-check my work before sending it out.', false),
('boh', 'Attention to Detail', 'I am very particular about hygiene and cleanliness.', false),
('boh', 'Attention to Detail', 'I check temperatures consistently.', false),
('boh', 'Attention to Detail', 'I taste everything before serving.', false),
('boh', 'Attention to Detail', 'I organize the walk-in perfectly.', false),
('boh', 'Attention to Detail', 'I sharpen my knives daily.', false),
('boh', 'Attention to Detail', 'I weigh ingredients precisely.', false),
('boh', 'Attention to Detail', 'I check expiration dates religiously.', false),
('boh', 'Attention to Detail', 'I notice if a plate is chipped or dirty.', false),
('boh', 'Attention to Detail', 'I follow HACCP guidelines strictly.', false),
('boh', 'Attention to Detail', 'I garnish every dish perfectly.', false),
('boh', 'Attention to Detail', 'I ensure uniform knife cuts.', false),
('boh', 'Attention to Detail', 'I protect against cross-contamination.', false),
('boh', 'Attention to Detail', 'I notice if a coworker is doing something unsafe.', false),
('boh', 'Attention to Detail', 'I label and date everything I prep.', false),
('boh', 'Attention to Detail', 'I clean as I go.', false),

-- Reliability / Work Ethic (20)
('boh', 'Reliability', 'I am never late for work.', false),
('boh', 'Reliability', 'I always finish what I start.', false),
('boh', 'Reliability', 'You can count on me to show up even when I''m tired.', false),
('boh', 'Reliability', 'I take responsibility for my mistakes.', false),
('boh', 'Reliability', 'I rarely call in sick.', false),
('boh', 'Reliability', 'I follow safety rules even when no one is watching.', false),
('boh', 'Reliability', 'I prep my station thoroughly before every shift.', false),
('boh', 'Reliability', 'I am consistent in the quality of my work.', false),
('boh', 'Reliability', 'I respect company property and equipment.', false),
('boh', 'Reliability', 'I always tell the truth to my supervisors.', false),
('boh', 'Reliability', 'I am committed to my job for the long term.', false),
('boh', 'Reliability', 'I do what I say I will do.', false),
('boh', 'Reliability', 'I work just as hard when the Chef is away.', false),
('boh', 'Reliability', 'I minimise food waste.', false),
('boh', 'Reliability', 'I recycle and dispose of waste correctly.', false),
('boh', 'Reliability', 'I maintain my uniform cleanliness.', false),
('boh', 'Reliability', 'I ask for more work when I am done.', false),
('boh', 'Reliability', 'I conserve energy and water.', false),
('boh', 'Reliability', 'I am honest about theft or pilferage.', false),
('boh', 'Reliability', 'I view cooking as a career, not just a job.', false),

-- Integrity / Safety (15)
('boh', 'Reliability', 'I would report a safety hazard immediately.', false),
('boh', 'Reliability', 'I effectively clean closing shifts.', false),
('boh', 'Reliability', 'I handle expensive ingredients with care.', false),
('boh', 'Reliability', 'I follow cooling procedures to prevent bacteria.', false),
('boh', 'Reliability', 'I wash my hands frequently.', false),
('boh', 'Reliability', 'I wear non-slip shoes for safety.', false),
('boh', 'Reliability', 'I help closing duties even if they are not mine.', false),
('boh', 'Reliability', 'I respect dietary restrictions (allergies) seriously.', false),
('boh', 'Reliability', 'I never compromise on food quality.', false),
('boh', 'Reliability', 'I am honest about breakage.', false),
('boh', 'Reliability', 'I handle chemicals safely.', false),
('boh', 'Reliability', 'I respect the personal space of others.', false),
('boh', 'Reliability', 'I lock up properly if I am last to leave.', false),
('boh', 'Reliability', 'I return borrowed equipment clean.', false),
('boh', 'Reliability', 'I set a good example for others.', false),

-- Validity (5)
('boh', 'Validity', 'I have never made a mistake while cooking or cleaning.', true),
('boh', 'Validity', 'I never get tired, no matter how hard I work.', true),
('boh', 'Validity', 'I check my phone zero times during a shift.', true),
('boh', 'Validity', 'I have never disagreed with a supervisor.', true),
('boh', 'Validity', 'I have never dropped anything in the kitchen.', true);
