
-- Social Media Manager (SMM) Assessment Questions (120 Questions)
-- To be run AFTER adding 'smm' to the role constraints.

INSERT INTO assessment_questions (role_type, category, question_text, is_validity) VALUES
-- Content Strategy & Creativity (20)
('smm', 'Content Strategy', 'I believe quality content is always better than quantity.', false),
('smm', 'Content Strategy', 'I can repurposed one piece of content into five different formats.', false),
('smm', 'Content Strategy', 'I prioritize storytelling over hard selling in captions.', false),
('smm', 'Content Strategy', 'I research hashtags before every post.', false),
('smm', 'Content Strategy', 'I plan my content calendar at least two weeks in advance.', false),
('smm', 'Content Strategy', 'I understand why a Reel performs differently than a Carousel.', false),
('smm', 'Content Strategy', 'I can spot a visual trend before it goes mainstream.', false),
('smm', 'Content Strategy', 'I believe user-generated content (UGC) is more authentic than polished ads.', false),
('smm', 'Content Strategy', 'I check for typos three times before hitting publish.', false),
('smm', 'Content Strategy', 'I understand the difference between reach and impressions.', false),
('smm', 'Content Strategy', 'I tailor my tone of voice for LinkedIn versus TikTok.', false),
('smm', 'Content Strategy', 'I use templates to speed up design workflow.', false),
('smm', 'Content Strategy', 'I believe consistency is the key to algorithm growth.', false),
('smm', 'Content Strategy', 'I audit competitor accounts regularly for inspiration.', false),
('smm', 'Content Strategy', 'I save trending audio for future use.', false),
('smm', 'Content Strategy', 'I can edit a video on my phone in under 15 minutes.', false),
('smm', 'Content Strategy', 'I understand the importance of a hook in the first 3 seconds.', false),
('smm', 'Content Strategy', 'I always include a clear Call to Action (CTA).', false),
('smm', 'Content Strategy', 'I balance promotional content with educational or entertaining posts.', false),
('smm', 'Content Strategy', 'I believe video content is non-negotiable in modern marketing.', false),

-- Community Management (20)
('smm', 'Community', 'I respond to every single comment on a post.', false),
('smm', 'Community', 'I use DMs to build personal relationships with followers.', false),
('smm', 'Community', 'I know how to handle a negative comment publicly without sounding defensive.', false),
('smm', 'Community', 'I engage with other accounts in my niche daily.', false),
('smm', 'Community', 'I believe community building is more valuable than viral hits.', false),
('smm', 'Community', 'I monitor brand mentions even if we are not tagged.', false),
('smm', 'Community', 'I create polls and stickers to encourage engagement.', false),
('smm', 'Community', 'I thank users who share our content in their stories.', false),
('smm', 'Community', 'I can turn a customer complaint into a public win.', false),
('smm', 'Community', 'I identify and nurture brand ambassadors.', false),
('smm', 'Community', 'I ask questions in captions to spark conversation.', false),
('smm', 'Community', 'I protect the brand reputation at all costs.', false),
('smm', 'Community', 'I hide spam comments immediately.', false),
('smm', 'Community', 'I verify winners of giveaways transparently.', false),
('smm', 'Community', 'I use pinned comments to highlight positive feedback.', false),
('smm', 'Community', 'I treat followers like guests in a restaurant.', false),
('smm', 'Community', 'I am patient with repetitive questions in DMs.', false),
('smm', 'Community', 'I alert management immediately if a crisis is brewing online.', false),
('smm', 'Community', 'I maintain a FAQ list to speed up responses.', false),
('smm', 'Community', 'I believe engagement rate is a better metric than follower count.', false),

-- Analytics & ROI (20)
('smm', 'Analytics', 'I review insights weekly to see what worked.', false),
('smm', 'Analytics', 'I understand what CAC (Customer Acquisition Cost) means.', false),
('smm', 'Analytics', 'I track website clicks from social bio links.', false),
('smm', 'Analytics', 'I A/B test different captions or headlines.', false),
('smm', 'Analytics', 'I know the best time of day to post for my specific audience.', false),
('smm', 'Analytics', 'I can explain why a post flopped without making excuses.', false),
('smm', 'Analytics', 'I use UTM parameters to track campaign success.', false),
('smm', 'Analytics', 'I focus on saves and shares more than likes.', false),
('smm', 'Analytics', 'I can calculate the engagement rate of a post manually.', false),
('smm', 'Analytics', 'I adjust my strategy based on monthly data reports.', false),
('smm', 'Analytics', 'I understand the impact of paid reach vs organic reach.', false),
('smm', 'Analytics', 'I monitor follower growth rate trends.', false),
('smm', 'Analytics', 'I analyze audience demographics to refine targeting.', false),
('smm', 'Analytics', 'I report valid ROI metrics to stakeholders.', false),
('smm', 'Analytics', 'I ignore vanity metrics that don''t drive business goals.', false),
('smm', 'Analytics', 'I track retention rate of video viewers.', false),
('smm', 'Analytics', 'I use social listening tools to track sentiment.', false),
('smm', 'Analytics', 'I believe data should drive creativity, not kill it.', false),
('smm', 'Analytics', 'I optimize profile bio for search (SEO).', false),
('smm', 'Analytics', 'I document wins and losses for future reference.', false),

-- Brand Voice & Aesthetics (20)
('smm', 'Brand', 'I can switch between a professional and playful tone as needed.', false),
('smm', 'Brand', 'I ensure all visuals align with the brand color palette.', false),
('smm', 'Brand', 'I prefer high-resolution original photography over stock photos.', false),
('smm', 'Brand', 'I proofread content to ensure it sounds like "us".', false),
('smm', 'Brand', 'I am protective of the brand logo usage.', false),
('smm', 'Brand', 'I believe the grid layout still matters for first impressions.', false),
('smm', 'Brand', 'I use font pairings that are on-brand.', false),
('smm', 'Brand', 'I avoid using slang that doesn''t fit the target audience.', false),
('smm', 'Brand', 'I create a style guide if one doesn''t exist.', false),
('smm', 'Brand', 'I evaluate partnerships to ensure brand alignment.', false),
('smm', 'Brand', 'I keep the highlight covers updated and uniform.', false),
('smm', 'Brand', 'I ensure accessibility (alt text) is part of the brand standard.', false),
('smm', 'Brand', 'I spot inconsistency in messaging immediately.', false),
('smm', 'Brand', 'I believe every post must add value to the follower.', false),
('smm', 'Brand', 'I stay true to brand values during social/political trends.', false),
('smm', 'Brand', 'I curate the "Following" list to reflect brand interests.', false),
('smm', 'Brand', 'I refresh the bio link regularly.', false),
('smm', 'Brand', 'I ensure video captions match the brand font.', false),
('smm', 'Brand', 'I treat the social profile as a digital storefront.', false),
('smm', 'Brand', 'I avoid cluttering visuals with too much text.', false),

-- Adaptability & Trends (20)
('smm', 'Adaptability', 'I consume social media content as a user to stay relevant.', false),
('smm', 'Adaptability', 'I am willing to pivot strategy if a platform changes (e.g., Tikok ban).', false),
('smm', 'Adaptability', 'I experiment with new features (e.g., Threads, Broadcast Channels).', false),
('smm', 'Adaptability', 'I don''t jump on every trend if it doesn''t fit the brand.', false),
('smm', 'Adaptability', 'I learn new editing apps constantly.', false),
('smm', 'Adaptability', 'I can work efficiently on mobile or desktop.', false),
('smm', 'Adaptability', 'I stay updated on platform algorithm updates.', false),
('smm', 'Adaptability', 'I am comfortable begin on camera if needed.', false),
('smm', 'Adaptability', 'I handle copyright changes (music) proactively.', false),
('smm', 'Adaptability', 'I collaborate with influencers seamlessly.', false),
('smm', 'Adaptability', 'I can create content in real-time at events.', false),
('smm', 'Adaptability', 'I find creative workarounds for technical glitches.', false),
('smm', 'Adaptability', 'I balance scheduled content with real-time updates.', false),
('smm', 'Adaptability', 'I embrace AI tools to improve efficiency, not replace creativity.', false),
('smm', 'Adaptability', 'I seek feedback from the team on new ideas.', false),
('smm', 'Adaptability', 'I accept that social media never sleeps but I set boundaries.', false),
('smm', 'Adaptability', 'I view competitors as case studies.', false),
('smm', 'Adaptability', 'I am resourceful with limited budgets.', false),
('smm', 'Adaptability', 'I can explain complex social trends to non-digital bosses.', false),
('smm', 'Adaptability', 'I enjoy the fast-paced nature of digital marketing.', false),

-- Validity (20)
('smm', 'Validity', 'I have never had a post get zero likes.', true),
('smm', 'Validity', 'I know every single person on the internet.', true),
('smm', 'Validity', 'I never check my phone notifications.', true),
('smm', 'Validity', 'I have never made a typo.', true),
('smm', 'Validity', 'I am the CEO of Instagram.', true),
('smm', 'Validity', 'I never experience creative block.', true),
('smm', 'Validity', 'I have 1 billion followers.', true),
('smm', 'Validity', 'I can upload content with my mind.', true),
('smm', 'Validity', 'I have never felt overwhelmed by social media.', true),
('smm', 'Validity', 'I like every single comment I see.', true),
('smm', 'Validity', 'I have never used a hashtag.', true),
('smm', 'Validity', 'I know the algorithm perfectly.', true),
('smm', 'Validity', 'I never sleep.', true),
('smm', 'Validity', 'I have never scrolled aimlessly.', true),
('smm', 'Validity', 'I am a robot.', true),
('smm', 'Validity', 'I never feel the need to unplug.', true),
('smm', 'Validity', 'I have never deleted a post.', true),
('smm', 'Validity', 'I am perfect.', true),
('smm', 'Validity', 'I never use emoji.', true),
('smm', 'Validity', 'I remember every tweet I ever wrote.', true);
