-- Insert Assessment Questions
-- Front of House (40 Questions)
INSERT INTO assessment_questions (role_type, category, question_text, is_validity) VALUES
('foh', 'Cooperativeness', 'I enjoy working closely with others to get the job done.', false),
('foh', 'Cooperativeness', 'I am always willing to help a coworker, even if I am busy.', false),
('foh', 'Cooperativeness', 'I prefer working in a team rather than alone.', false),
('foh', 'Cooperativeness', 'It is important to me that everyone on the team gets along.', false),
('foh', 'Cooperativeness', 'I often put the team needs above my own.', false),
('foh', 'Cooperativeness', 'I don''t mind taking instructions from others.', false),
('foh', 'Personal Diplomacy', 'I can easily talk to people I have just met.', false),
('foh', 'Personal Diplomacy', 'I am good at sensing how others are feeling.', false),
('foh', 'Personal Diplomacy', 'I know how to deliver bad news without making people angry.', false),
('foh', 'Personal Diplomacy', 'I am polite even when people are rude to me.', false),
('foh', 'Personal Diplomacy', 'I enjoy meeting new people every day.', false),
('foh', 'Personal Diplomacy', 'I can easily find common ground with anyone.', false),
('foh', 'Patience', 'I rarely get annoyed by slow customers.', false),
('foh', 'Patience', 'I can wait for long periods without getting frustrated.', false),
('foh', 'Patience', 'I stay calm when things don''t go as planned.', false),
('foh', 'Patience', 'I don''t mind explaining things multiple times to guests.', false),
('foh', 'Patience', 'I take my time to listen to customer complaints fully.', false),
('foh', 'Patience', 'Rushing through tasks makes me uncomfortable; I prefer a steady pace.', false),
('foh', 'Relaxed Attitude', 'I stay calm even when the restaurant is extremely busy.', false),
('foh', 'Relaxed Attitude', 'Loud noises and crowds do not bother me.', false),
('foh', 'Relaxed Attitude', 'I can handle multiple tables at once without panicking.', false),
('foh', 'Relaxed Attitude', 'I rarely feel overwhelmed by pressure.', false),
('foh', 'Relaxed Attitude', 'I find it easy to relax after a hard day''s work.', false),
('foh', 'Relaxed Attitude', 'Unexpected problems are just challenges to solve.', false),
('foh', 'Sales Aptitude', 'I enjoy persuading people to try new things.', false),
('foh', 'Sales Aptitude', 'I feel comfortable suggesting expensive items to customers.', false),
('foh', 'Sales Aptitude', 'I see sales as helping the customer have a better experience.', false),
('foh', 'Sales Aptitude', 'I am confident in my ability to sell.', false),
('foh', 'Sales Aptitude', 'I like the challenge of increasing the bill size.', false),
('foh', 'Sales Aptitude', 'I can enthusiastically describe menu items.', false),
('foh', 'Achievement', 'I always try to be the best at what I do.', false),
('foh', 'Achievement', 'I set high standards for myself.', false),
('foh', 'Achievement', 'I am constantly looking for ways to improve my performance.', false),
('foh', 'Achievement', 'Getting recognized for good work is important to me.', false),
('foh', 'Achievement', 'I enjoy competition and winning.', false),
('foh', 'Achievement', 'I am willing to work hard to get a promotion.', false),
('foh', 'Validity', 'I have never once been annoyed by a customer.', true),
('foh', 'Validity', 'I have never made a mistake at work.', true),
('foh', 'Validity', 'I like every single person I have ever met.', true),
('foh', 'Validity', 'I am always happy, regardless of the situation.', true);

-- Back of House (40 Questions)
INSERT INTO assessment_questions (role_type, category, question_text, is_validity) VALUES
('boh', 'Patience', 'I can perform repetitive tasks without getting bored.', false),
('boh', 'Patience', 'I don''t mind waiting for others to finish their part of the job.', false),
('boh', 'Patience', 'I stay calm when orders pile up.', false),
('boh', 'Patience', 'I take the time to do things right, even when busy.', false),
('boh', 'Patience', 'I rarely lose my temper in the kitchen.', false),
('boh', 'Patience', 'I can handle long shifts without complaining.', false),
('boh', 'Stress Tolerance', 'I work best when under pressure.', false),
('boh', 'Stress Tolerance', 'A busy kitchen environment excites me.', false),
('boh', 'Stress Tolerance', 'I can make quick decisions during a rush.', false),
('boh', 'Stress Tolerance', 'Loud and chaotic environments do not distract me.', false),
('boh', 'Stress Tolerance', 'I recover quickly after a stressful service.', false),
('boh', 'Stress Tolerance', 'I can multitask effectively without dropping the ball.', false),
('boh', 'Teamwork', 'I communicate clearly with my station partners.', false),
('boh', 'Teamwork', 'I am willing to cover for a coworker if they are behind.', false),
('boh', 'Teamwork', 'I respect the hierarchy in the kitchen.', false),
('boh', 'Teamwork', 'I believe the team''s success is more important than my own credit.', false),
('boh', 'Teamwork', 'I listen carefully to the Chef''s instructions.', false),
('boh', 'Teamwork', 'I avoid workplace gossip or conflict.', false),
('boh', 'Attention to Detail', 'I always follow recipes exactly as written.', false),
('boh', 'Attention to Detail', 'I notice small details that others might miss.', false),
('boh', 'Attention to Detail', 'Presentation is just as important as taste to me.', false),
('boh', 'Attention to Detail', 'I keep my workspace perfectly organized.', false),
('boh', 'Attention to Detail', 'I double-check my work before sending it out.', false),
('boh', 'Attention to Detail', 'I am very particular about hygiene and cleanliness.', false),
('boh', 'Reliability', 'I am never late for work.', false),
('boh', 'Reliability', 'I always finish what I start.', false),
('boh', 'Reliability', 'You can count on me to show up even when I''m tired.', false),
('boh', 'Reliability', 'I take responsibility for my mistakes.', false),
('boh', 'Reliability', 'I rarely call in sick.', false),
('boh', 'Reliability', 'I follow safety rules even when no one is watching.', false),
('boh', 'Reliability', 'I prep my station thoroughly before every shift.', false),
('boh', 'Reliability', 'I am consistent in the quality of my work.', false),
('boh', 'Reliability', 'I respect company property and equipment.', false),
('boh', 'Reliability', 'I always tell the truth to my supervisors.', false),
('boh', 'Reliability', 'I am committed to my job for the long term.', false),
('boh', 'Reliability', 'I do what I say I will do.', false),
('boh', 'Validity', 'I have never made a mistake while cooking or cleaning.', true),
('boh', 'Validity', 'I never get tired, no matter how hard I work.', true),
('boh', 'Validity', 'I check my phone zero times during a shift.', true),
('boh', 'Validity', 'I have never disagreed with a supervisor.', true);
